[project]
name = "whispersviolins"
version = "1.0.0"
description = "Transcribe audio files with local LLM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-whisper>=20250625",
    "pyinstaller>=6.16.0",
    "pyqt6>=6.10.0",
]
